url: https://localhost:4000
baseurl: /contribe/

# Site settings
title: Contribe
email: brian.ranney@contribe.se
description: "Contribe - Vi förenklar framtiden"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3397b9
  secondary: c39
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Roger Gordin
  pic: roger
  position: VD
  social:
    - title: linkedin
      url: https://www.linkedin.com/pub/roger-gordin/2/a21/a83
    - title: envelope-o
      url: mailto:roger.gordin@contribe.se

- name: Marcus Nilsson
  pic: marcus
  position: Konsultchef
  social:
    - title: linkedin
      url: https://se.linkedin.com/pub/marcus-nilsson/61/70b/561
    - title: envelope-o
      url: mailto:marcus.nilsson@contribe.se

- name: Carin Håkansson
  pic: carin
  position: Konsultchef
  social:
    - title: linkedin
      url: https://se.linkedin.com/pub/carin-h%C3%A5kansson/9/b35/353
    - title: envelope-o
      url: mailto:carin.hakansson@contribe.se

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/contribe

# Build settings
markdown: kramdown
permalink: pretty